### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by jspenc72**
This bumps ecdsa to >=0.16.0 for easier dependency resolution.

### CODE REVIEW

**Review by cardosofede — APPROVED** [review]
LGTM

**Comment by cardosofede** [comment]
@eyqs can we merge this pr? I have issues with this dependency too.

**Review by felixfaisal — APPROVED** [review]
We are also blocked by this dependency, Would be great if this gets merged :) 
Also locally did the changes and ran the tests, All passed.

**Comment by jaymansfield** [comment]
Can this be merged please?? @jiajames

**Comment by BrendanChou** [comment]
Fixed in https://github.com/dydxprotocol/dydx-v3-python/pull/184

**Pull request closed without merging**
